services:
  jupyterhub_test_phu:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    # image: quay.io/jupyterhub/jupyterhub
    # container_name: jupyterhub_test_phu
    ports:
      - "7000:8000"
    volumes:
      - ./jupyterhub_data/:/srv/share_data
      # - ./user/:/srv/
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # - /srv/share_data:/srv/share_data
      - ./phundh/:/home/phundh
      - ./bob/:/home/bob
      - ./alice/:/home/alice
      - ./minhnh/:/home/minhnh
      
      #- ./jupyterhub_config.py: /srv/jupyterhub
    # user: "1000:1000"
    deploy:
      #mode: replicated
      #replicas: 2
      resources:
        reservations:
          memory: 100G  # Sử dụng "memory" tại đây, không phải trong "devices"
          devices:
            - driver: nvidia
              device_ids: ['6','7']
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

      DOCKER_NETWORK_NAME: jupyterhub-network
      # DOCKER_NOTEBOOK_IMAGE: jupyter/minimal-notebook:latest
      
    restart: unless-stopped
    networks:
      - jupyterhub-network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "70:80"  # Forward HTTP requests to Nginx on port 80
      - "743:443"  # Forward HTTPS requests to Nginx on port 443
    depends_on:
      - jupyterhub_test_phu
    restart: unless-stopped
    networks:
      - jupyterhub-network

# volumes:
#   jupyterhub_data: {}
#   phundh: {}
#   bob: {}
#   alice: {}
#   minhnh: {}
    
networks:
  jupyterhub-network:
    driver: bridge
    external: true
    name: jupyterhub-network